stages:
  - test
  - build
  - deploy

.golang_common: &golang_common
  image: golang
  variables:
    GOOS: linux
    GOARCH: amd64
    GO111MODULE: off

test PrinterScript:
  <<: *golang_common
  stage: test
  script:
    - cd printerscript
    - go get github.com/antlr/antlr4/runtime/Go/antlr
    - go test

test MSF:
  <<: *golang_common
  stage: test
  script:
    - cd msf
    - go test

build:
  <<: *golang_common
  stage: build
  artifacts:
    paths:
      - ps-postprocess
    expire_in: 1 day
  script:
    - go get github.com/antlr/antlr4/runtime/Go/antlr
    - go build

deploy dev:
  image: napp/docker-aws-cli
  stage: deploy
  dependencies:
    - build
  only:
    - master
  environment:
    name: development
  script:
    - aws s3 cp ./ps-postprocess s3://$AWS_BUCKET/go-utils/ps-postprocess-development

deploy prod:
  image: napp/docker-aws-cli
  stage: deploy
  dependencies:
    - build
  only:
    - production
  environment:
    name: production
  script:
    - aws s3 cp ./ps-postprocess s3://$AWS_BUCKET/go-utils/ps-postprocess-production
