name: Create Release of Library

on:
  push:
    branches: ['main']
  workflow_dispatch:

env:
  DEPLOY_ENV: production
  BUCKET_NAME: opal-tide

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test

  licensebot:
    name: Licensebot Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/license-check

  build:
    name: Compile
    runs-on: ubuntu-latest
    needs: ['test', 'licensebot']
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - uses: ./.github/actions/build
        with:
          os: windows
          build-suffix: .exe
      - uses: ./.github/actions/build
        with:
          os: darwin
          build-suffix: -darwin

  deploy:
    name: Upload binary
    environment: production
    concurrency: deploy_prod
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    needs: ['build']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: ps-postprocess
      - uses: actions/download-artifact@v3
        with:
          name: ps-postprocess.exe
      - uses: actions/download-artifact@v3
        with:
          name: ps-postprocess-darwin
      - name: Get Version
        id: get-version
        run: |
          echo "version=$(cat version.txt | tr -d '\n')" >> $GITHUB_OUTPUT
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{secrets.AWS_ROLE}}
          aws-region: ${{secrets.AWS_REGION}}
      - name: Upload binaries to S3 if does not exist
        run: |
          EXISTS=true
          aws s3 ls s3://${{env.BUCKET_NAME}}/ps-postprocess/${{steps.get-version.outputs.version}}/linux/amd64/ps-postprocess || aws s3 ls s3://${{env.BUCKET_NAME}}/ps-postprocess/${{steps.get-version.outputs.version}}}/windows/amd64/ps-postprocess.exe || aws s3 ls s3://${{env.BUCKET_NAME}}/ps-postprocess/${{steps.get-version.outputs.version}}}/darwin/amd64/ps-postprocess || EXISTS=false
          if [ $EXISTS == true ]; then
            echo "Library version already exists."
            exit 1
          fi
          echo "Existing version has not been published"
          aws s3 cp ./ps-postprocess s3://${{env.BUCKET_NAME}}/ps-postprocess/${{steps.get-version.outputs.version}}/linux/amd64/ps-postprocess
          aws s3 cp ./ps-postprocess.exe s3://${{env.BUCKET_NAME}}/ps-postprocess/${{steps.get-version.outputs.version}}}/windows/amd64/ps-postprocess.exe
          aws s3 cp ./ps-postprocess-darwin s3://${{env.BUCKET_NAME}}/ps-postprocess/${{steps.get-version.outputs.version}}}/darwin/amd64/ps-postprocess

  licensebot_trigger:
    name: Trigger Licensebot
    environment: production
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    concurrency: licensebot_trigger_prod
    needs: ['deploy']
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/license-publish
        with:
          deploy-env: ${{env.DEPLOY_ENV}}
          aws-role: ${{secrets.AWS_ROLE}}
          aws-region: ${{secrets.AWS_REGION}}
          function-name: ${{secrets.LICENSEBOT_ARN}}
          s3-source-bucket: ${{secrets.LICENSEBOT_S3_SOURCE_BUCKET}}
          s3-source-key: ${{env.DEPLOY_ENV}}/ps-postprocess.json
          s3-output-bucket: ${{secrets.LICENSEBOT_S3_OUTPUT_BUCKET}}
