name: Create Release of Library

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test

  licensebot:
    name: Licensebot Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/license-check

  build:
    name: Compile
    runs-on: ubuntu-latest
    needs: ['test', 'licensebot']
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - uses: ./.github/actions/build
        with:
          os: windows
          build-suffix: .exe
      - uses: ./.github/actions/build
        with:
          os: darwin
          build-suffix: -darwin

  deploy:
    name: Upload binary
    environment: production
    concurrency: deploy_main
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    needs: ['build']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: ps-postprocess
      - uses: actions/download-artifact@v4
        with:
          name: ps-postprocess.exe
      - uses: actions/download-artifact@v4
        with:
          name: ps-postprocess-darwin
      - name: Get Version
        id: get-version
        run: |
          echo "version=$(cat version.txt | tr -d '\n')" >> $GITHUB_OUTPUT
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_ROLE}}
          aws-region: ${{secrets.AWS_REGION}}
      - name: Upload binaries to S3 if does not exist
        env:
            S3_PATH: s3://${{secrets.S3_BUCKET}}/ps-postprocess/${{steps.get-version.outputs.version}}
        run: |
          EXISTS=true
          aws s3 ls ${{env.S3_PATH}}/linux/amd64/ps-postprocess || aws s3 ls ${{env.S3_PATH}}/windows/amd64/ps-postprocess.exe || aws s3 ls ${{env.S3_PATH}}/darwin/amd64/ps-postprocess || EXISTS=false
          if [ $EXISTS == true ]; then
            echo "Library version already exists."
            exit 1
          fi
          echo "Existing version has not been published"
          aws s3 cp ./ps-postprocess ${{env.S3_PATH}}/linux/amd64/ps-postprocess
          aws s3 cp ./ps-postprocess.exe ${{env.S3_PATH}}/windows/amd64/ps-postprocess.exe
          aws s3 cp ./ps-postprocess-darwin ${{env.S3_PATH}}/darwin/amd64/ps-postprocess
          aws s3 cp ./licenses.json ${{env.S3_PATH}}/licenses.json
