name: Build and Deploy (prod)

on:
  push:
    branches: ['production']

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test

  licensebot:
    name: Licensebot Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/license-check

  build:
    name: Compile
    runs-on: ubuntu-latest
    needs: ['test', 'licensebot']
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build

  deploy:
    name: Upload binary
    environment: production
    concurrency: deploy_prod
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    needs: ['build']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: ps-postprocess
      - uses: ./.github/actions/s3-upload
        with:
          aws-role: ${{secrets.AWS_ROLE}}
          aws-region: ${{secrets.AWS_REGION}}
          s3-bucket: ${{secrets.S3_BUCKET}}
          s3-key: go-utils/ps-postprocess-production
          binary-name: ps-postprocess
